### ISSUE TITLE
Recent rails commit benchmarks are not shown or are not running

### ISSUE THREAD

**Issue by jerryliu55** [ruby-bench/ruby-bench-web#193]
It seems like the latest rails commit benchmark is from Oct 3, 2016

**Comment by tgxworld** [comment]
The Rails commits are broken at the moment. I'll need to spend some time looking into them.

**Comment by bmarkons** [comment]
Following error occurs on `bundle install --without test doc job`

```
Gem::InstallError: ruby_dep requires Ruby version >= 2.2.5, ~> 2.2.
An error occurred while installing ruby_dep (1.5.0), and Bundler cannot continue.
Make sure that `gem install ruby_dep -v '1.5.0'` succeeds before bundling.

```

I guess solution would be to bump ruby version or modify version of listen gem to 3.0.8 since thats the one which depends on ruby_dep.

**Comment by bmarkons** [comment]
This change broke it on Oct 3, 2016 (as @jerryliu55 noticed)  https://github.com/rails/rails/commit/ddddedc487912e33edb7d78aec6bcf99b1312c6d

**Comment by bmarkons** [comment]
I bumped ruby version to 2.4.1 and updated rails_trunk Dockerfile accordingly. Some of benchmarks (postgres) are running properly but some are failing (mysql and activecable). Logs can be seen on server.

Previous runs have been invalidated for recovered benchmarks because of ruby version change.

These specific benchmark errors need to be fixed.

**Comment by bmarkons** [comment]
This error is raised on `ActiveRecord::Schema.define` with mysql2:

```
/rails/activerecord/lib/active_record/connection_adapters/mysql/database_statements.rb:83:in `block in exec_stmt_and_free': NoMethodError: undefined method `free' for #<Mysql2::Result:0x007f687469cb78>: SELECT  `ar_internal_metadata`.* FROM `ar_internal_metadata` WHERE `ar_internal_metadata`.`key` = ? LIMIT ? (ActiveRecord::StatementInvalid)
        from /rails/activerecord/lib/active_record/connection_adapters/abstract_adapter.rb:580:in `block (2 levels) in log'
        from /root/.rbenv/versions/2.4.1/lib/ruby/2.4.0/monitor.rb:214:in `mon_synchronize'
        from /rails/activerecord/lib/active_record/connection_adapters/abstract_adapter.rb:579:in `block in log'
        from /rails/activesupport/lib/active_support/notifications/instrumenter.rb:21:in `instrument'
        from /rails/activerecord/lib/active_record/connection_adapters/abstract_adapter.rb:571:in `log'
        from /rails/activerecord/lib/active_record/connection_adapters/mysql/database_statements.rb:59:in `exec_stmt_and_free'
        from /rails/activerecord/lib/active_record/connection_adapters/mysql/database_statements.rb:31:in `exec_query'
        from /rails/activerecord/lib/active_record/connection_adapters/abstract/database_statements.rb:405:in `select_prepared'
        from /rails/activerecord/lib/active_record/connection_adapters/abstract/database_statements.rb:40:in `select_all'
        from /rails/activerecord/lib/active_record/connection_adapters/abstract/query_cache.rb:97:in `select_all'
        from /rails/activerecord/lib/active_record/connection_adapters/mysql/database_statements.rb:10:in `select_all'
        from /rails/activerecord/lib/active_record/querying.rb:39:in `find_by_sql'
        from /rails/activerecord/lib/active_record/relation.rb:660:in `exec_queries'
        from /rails/activerecord/lib/active_record/relation.rb:547:in `load'
        from /rails/activerecord/lib/active_record/relation.rb:256:in `records'
        from /rails/activerecord/lib/active_record/relation/finder_methods.rb:515:in `find_take'
        from /rails/activerecord/lib/active_record/relation/finder_methods.rb:100:in `take'
        from /rails/activerecord/lib/active_record/relation/finder_methods.rb:78:in `find_by'
        from /rails/activerecord/lib/active_record/relation.rb:234:in `find_or_initialize_by'
        from /rails/activerecord/lib/active_record/querying.rb:6:in `find_or_initialize_by'
        from /rails/activerecord/lib/active_record/internal_metadata.rb:18:in `[]='
        from /rails/activerecord/lib/active_record/schema.rb:56:in `define'
        from /rails/activerecord/lib/active_record/schema.rb:44:in `define'
        from /ruby-bench-suite/rails/benchmarks/bm_activerecord_validations_valid.rb:8:in `<main>'
```

**Comment by tgxworld** [comment]
Thanks for squashing all these :bug:

**Comment by bmarkons** [comment]
@tgxworld no problem :wink: 

Actually I didn't fix ActionCable. I fixed only mysql and scaffold benchmarks. Therefore I think this issue shouldn't be closed yet.

**Comment by bmarkons** [comment]
I've opened this more specific one https://github.com/ruby-bench/ruby-bench-web/issues/240

Closing this.
