### ISSUE TITLE
Can't display chart for Rails commits

### ISSUE THREAD

**Issue by bmarkons** [ruby-bench/ruby-bench-web#200]
Error occurs when trying to unpack cached chart from redis.

It only happens when fetching chart for Rails commits.

Here's the error log:

```
Started GET "/rails/rails/commits?result_type=actioncable%2Fredis&display_count=2000&_=1495453713713" for 172.68.154.111 at 2017-05-22 11:49:09 +0000
Processing by ReposController#commits as JS
  Parameters: {"result_type"=>"actioncable/redis", "display_count"=>"2000", "_"=>"1495453713713", "organization_name"=>"rails", "repo_name"=>"rails"}
Completed 500 Internal Server Error in 40ms (ActiveRecord: 0.0ms)
** [Bugsnag] Notifying https://notify.bugsnag.com of MessagePack::MalformedFormatError

MessagePack::MalformedFormatError (168279 extra bytes after the deserialized object):

app/controllers/repos_controller.rb:31:in `unpack'
app/controllers/repos_controller.rb:31:in `block in commits'
app/controllers/repos_controller.rb:27:in `commits'
```

**Comment by bmarkons** [comment]
Clearing redis cache fixed the issue.
