### ISSUE TITLE
ActionCable benchmarks are broken

### ISSUE THREAD

**Issue by bmarkons** [ruby-bench/ruby-bench-web#240]
Following error is raised in ActionCable benchmarks:
```
/ruby-bench-suite/rails/benchmarks/support/actioncable_helpers.rb:34:in `<top (required)>': undefined method `channel_paths=' for #<ActionCable::Server::Configuration:0x007f17623a12b0> (NoMethodError)
        from /ruby-bench-suite/rails/benchmarks/bm_actioncable_redis.rb:5:in `require_relative'
        from /ruby-bench-suite/rails/benchmarks/bm_actioncable_redis.rb:5:in `<main>'
```

**Comment by robin850** [comment]
Hi @bmarkons,

It looks like this method was removed in https://github.com/rails/rails/commit/a8df1bc345bf062e98bda64ef9638f65292c4b56. Actually, it was not part of the public API so this explains why it hasn't gone through a deprecation cycle and it now fails.

I'm not sure this is needed anymore but I didn't test though. I hop this helped you ! :-)

**Comment by bmarkons** [comment]
Thanks @robin850 :) I suppose we should remove that method call then :+1:
